services:
  - type: web
    name: contextswap-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    autoDeploy: true
